channels:
- conda-forge
dependencies:
- python=3.13.7
- pip<=25.2
- pip:
  - mlflow==3.6.0
  - bcrypt==5.0.0
  - cloudpickle==3.1.2
  - cryptography==45.0.5
  - defusedxml==0.7.1
  - dill==0.4.0
  - google-cloud-aiplatform==1.128.0
  - google-cloud-billing==1.17.0
  - google-cloud-firestore==2.21.0
  - google-cloud-logging==3.12.1
  - google-cloud-support==0.2.0
  - grpcio-status==1.74.0
  - ipywidgets==8.1.7
  - lightgbm==4.6.0
  - matplotlib==3.7.0
  - numpy==2.2.6
  - opentelemetry-exporter-otlp==1.38.0
  - pandas==2.3.3
  - psutil==7.0.0
  - pyarrow==22.0.0
  - pyreadline3==3.5.4
  - scikit-learn==1.7.2
  - scipy==1.16.1
  - seaborn==0.12.0
  - torch==2.7.1
  - tqdm==4.67.1
name: mlflow-env
